UserManagement.Web/Areas/UserManagementAdmin/Pages/Attendence/Display.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserManagement.Web.Code;

namespace Christmas_Application.Web.Areas.UserManagementAdmin.Pages.Attendence
{
    public class DisplayModel : BasePageModel
    {
        public void OnGet()
        {
        }
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Attendence/Edite.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserManagement.Web.Code;

namespace Christmas_Application.Web.Areas.UserManagementAdmin.Pages.Attendence
{
    public class EditeModel : BasePageModel
    {
        public void OnGet()
        {
        }
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Policies/Create.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using UserManagement.Application;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using PoliciesManagementResources = UserManagement.Localization.PoliciesManagement.PoliciesManagement;
using SharedResources = Common.Localization.Shared.Shared;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Policies
{
    public class CreateModel : BasePageModel
    {
        public CreateModel(IPolicyService policyService,IRolesService rolesService)
        {
            Title = PoliciesManagementResources.Create_Title;
            PolicyService = policyService;
            RolesService = rolesService;
        }

        #region Dependencies
        public IPolicyService PolicyService { get; }
        public IRolesService RolesService { get; }
        #endregion

        #region Properties
        [BindProperty]
        public PolicyViewModel Input { set; get; } = new PolicyViewModel();

        public List<RoleViewModel> RolesList = new List<RoleViewModel>();

        #endregion

        #region Get
        public void OnGet()
        {
            RolesList = RolesService.GetAll();

        }
        #endregion

        #region Post
        public async Task<IActionResult> OnPostSubmit()
        {
            if (!ModelState.IsValid)
            {
                RolesList = RolesService.GetAll();
                return Page();
            }

            var result = await PolicyService.Save(new ReturnResult<PolicyViewModel>() { Value = Input });
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                RolesList = RolesService.GetAll();
                return Page();
            }

            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResources.CreateSuccess);

            return RedirectToPage(NavigationConstants.Pages.PolicyIndex, new { area = NavigationConstants.Area});
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });
        }
        #endregion

    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Policies/Display.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using PoliciesManagementResources = UserManagement.Localization.PoliciesManagement.PoliciesManagement;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Policies
{
    public class DisplayModel : BasePageModel
    {
        public DisplayModel(IPolicyService policyService)
        {
            Title = PoliciesManagementResources.Display_Title;
            PolicyService = policyService;
        }

        #region Dependencies
        public IPolicyService PolicyService { get; }
        #endregion

        #region Properties
        [BindProperty]
        public PolicyViewModel Input { set; get; } = new PolicyViewModel();

        #endregion

        #region Get
        public async Task<IActionResult> OnGet(int policyId)
        {
            var result = await PolicyService.GetById(policyId);
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                ShowMessage(CoreEnumerations.MessageTypes.danger, ModelState.GetErrors(" , "));

                return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });
            }
            Input = result.Value;
            return Page();
        }
        #endregion

        #region Post

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });
        }
        #endregion
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Policies/Edite.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using UserManagement.Application;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using PoliciesManagementResources = UserManagement.Localization.PoliciesManagement.PoliciesManagement;
using SharedResources = Common.Localization.Shared.Shared;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Policies
{
    public class EditeModel : BasePageModel
    {
        public EditeModel(IPolicyService policyService,IRolesService rolesService)
        {
            Title = PoliciesManagementResources.Edite_Title;

            PolicyService = policyService;
            RolesService = rolesService;
        }

        #region Dependencies
        public IPolicyService PolicyService { get; }
        public IRolesService RolesService { get; }

        #endregion

        #region Properties
        [BindProperty]
        public PolicyViewModel Input { set; get; } = new PolicyViewModel();
        public List<RoleViewModel> RolesList = new List<RoleViewModel>();

        #endregion

        #region Get
        public async Task<IActionResult> OnGet(int policyId)
        {
            var result = await PolicyService.GetById(policyId);
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                ShowMessage(CoreEnumerations.MessageTypes.danger, ModelState.GetErrors(" , "));

                return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });
            }
            Input = result.Value;
            RolesList = RolesService.GetAll();

            return Page();
        }
        #endregion

        #region Post
        public async Task<IActionResult> OnPostSubmit()
        {
            ModelState.Remove("Input.Name");

            if (!ModelState.IsValid)
            {
                RolesList = RolesService.GetAll();
                return Page();
            }

            var result = await PolicyService.Save(new ReturnResult<PolicyViewModel>() { Value = Input });
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                RolesList = RolesService.GetAll();
                return Page();
            }

            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResources.EditSuccess);

            return RedirectToPage(NavigationConstants.Pages.PolicyIndex, new { area = NavigationConstants.Area });
        }

        public async Task<IActionResult> OnPostRemove(int id)
        {
            ModelState.Remove("Input.Name");

            var result = await PolicyService.Delete(new ReturnResult<int> { Value = id });
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                RolesList = RolesService.GetAll();
                return Page();
            }
            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResources.DeleteSuccess);
            return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });

        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Policies/Index", new { area = "UserManagementAdmin" });
        }
        #endregion
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Roles/Create.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using RolesManagementResources = UserManagement.Localization.RolesManagement.RolesManagement;
using SharedResources = Common.Localization.Shared.Shared;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Roles
{
    public class CreateModel : BasePageModel
    {
        public CreateModel(IRolesService rolesService)
        {
            Title = RolesManagementResources.Create_Title;
            RolesService = rolesService;
        }

        #region Dependencies
        public IRolesService RolesService { get; }
        #endregion

        #region Properties
        [BindProperty]
        public RoleViewModel Input { set; get; } = new RoleViewModel();

        #endregion

        #region Get
        public void OnGet()
        {
        }
        #endregion

        #region Post
        public async Task<IActionResult> OnPostSubmit()
        {
            if (!ModelState.IsValid)
                return Page();

            var result = await RolesService.Add(new ReturnResult<RoleViewModel>() { Value = Input });
            ModelState.Merge(result);

            if (!ModelState.IsValid)
                return Page();

            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResources.CreateSuccess);

            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
        }
        #endregion
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Roles/Display.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using RolesManagementResources = UserManagement.Localization.RolesManagement.RolesManagement;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Roles
{
    public class DisplayModel : BasePageModel
    {
        public DisplayModel(IRolesService rolesService)
        {
            Title = RolesManagementResources.Display_Title;
            RolesService = rolesService;
        }

        #region Dependencies
        public IRolesService RolesService { get; }
        #endregion

        #region Properties
        [BindProperty]
        public RoleViewModel Input { set; get; } = new RoleViewModel();
        #endregion

        #region Get
        public async Task<IActionResult> OnGet(string roleId)
        {
            var result = await RolesService.GetById(roleId);
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                ShowMessage(CoreEnumerations.MessageTypes.danger, ModelState.GetErrors(" , "));

                return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
            }
            Input = result.Value;
            return Page();
        }
        #endregion

        #region Post
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
        }
        #endregion
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Roles/Edite.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using RolesManagementResources = UserManagement.Localization.RolesManagement.RolesManagement;
using SharedResource = Common.Localization.Shared.Shared;

namespace UserManagement.Web.Areas.UserManagementAdmin.Pages.Roles
{
    public class EditeModel : BasePageModel
    {
        public EditeModel(IRolesService rolesService)
        {
            Title = RolesManagementResources.Edite_Title;
            RolesService = rolesService;
        }

        #region Dependencies
        public IRolesService RolesService { get; }
        #endregion

        #region Properties
        [BindProperty]
        public RoleViewModel Input { set; get; } = new RoleViewModel();

        #endregion

        #region Get
        public async Task<IActionResult> OnGet(string roleId)
        {
            var result =await RolesService.GetById(roleId);
            ModelState.Merge(result);

            if (!ModelState.IsValid)
            {
                ShowMessage(CoreEnumerations.MessageTypes.danger, ModelState.GetErrors(" , "));

                return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
            }
            Input = result.Value;
            return Page();
        }
        #endregion

        #region Post
        public async Task<IActionResult> OnPostSubmit()
        {
            if (!ModelState.IsValid)
                return Page();

            var result = await RolesService.Update(new ReturnResult<RoleViewModel>() { Value = Input });
            ModelState.Merge(result);
            
            if (!ModelState.IsValid)
                return Page();

            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResource.EditSuccess);

            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
        }

        public async Task<IActionResult> OnPostRemove(Guid id)
        {
            ModelState.Remove("Input.Name");

            var result = await RolesService.Delete(new ReturnResult<Guid> { Value = id });
            ModelState.Merge(result);

            if (!ModelState.IsValid)
                return Page();

            ShowMessage(CoreEnumerations.MessageTypes.info, SharedResource.DeleteSuccess);
            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });

        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Roles/Index", new { area = "UserManagementAdmin" });
        }

        #endregion
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Rules/Create.cshtml.cs
using CrossCutting.Core;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using UserManagement.Application.Services.Abstraction;
using UserManagement.Domain.ViewModels;
using UserManagement.Web.Code;
using RulesManagementResources = UserManagement.Localization.RulesManagement.RulesManagement;
using SharedResources = Common.Localization.Shared.Shared;

namespace Christmas_Application.Web.Areas.UserManagementAdmin.Pages.Rules
{
    public class CreateModel : BasePageModel
    {
            public CreateModel(IRuleService ruleService)
            {
                Title = RulesManagementResources.Create_Title;
                RuleService = ruleService;
            }

            #region Dependencies
            public IRuleService RuleService { get; }
            #endregion

            #region Properties
            [BindProperty]
            public RuleViewModel Input { set; get; } = new RuleViewModel();

            #endregion

            #region Get
            public void OnGet()
            {
            }
            #endregion

            #region Post
            public async Task<IActionResult> OnPostSubmit()
            {
                if (!ModelState.IsValid)
                    return Page();

                var result = await RuleService.Add(new ReturnResult<RuleViewModel>() { Value = Input });
                ModelState.Merge(result);

                if (!ModelState.IsValid)
                    return Page();

                ShowMessage(CoreEnumerations.MessageTypes.info, SharedResources.CreateSuccess);

                return RedirectToPage("/Rules/Index", new { area = "UserManagementAdmin" });
            }

            public IActionResult OnPostCancel()
            {
                return RedirectToPage("/Rules/Index", new { area = "UserManagementAdmin" });
            }
            #endregion
        }
    
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Rules/Display.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserManagement.Web.Code;

namespace Christmas_Application.Web.Areas.UserManagementAdmin.Pages.Rules
{
    public class DisplayModel : BasePageModel
    {
        public void OnGet()
        {
        }
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Rules/Edite.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserManagement.Web.Code;

namespace Christmas_Application.Web.Areas.UserManagementAdmin.Pages.Rules
{
    public class EditeModel : BasePageModel
    {
        public void OnGet()
        {
        }
    }
}

UserManagement.Web/Areas/UserManagementAdmin/Pages/Users/Edite.cshtml
@page "/Users/Edite/{userId?}"
@using Common.Localization.Shared
@using CrossCutting.Core.Globalization
@using UsersManagementResources = UserManagement.Localization.UsersManagement.UsersManagement;
@using SharedResources = Common.Localization.Shared.Shared;
@using UserManagement.Domain.Models
@model UserManagement.Web.Areas.UserManagementAdmin.Pages.Users.EditeModel
@{
}

@section Styles{
    <!-- Switchery -->
    <link href="~/TemplateManagement/vendors/switchery/dist/switchery.min.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/TemplateManagement/vendors/iCheck/skins/flat/green.css" rel="stylesheet" />
    <!--dropify-->
    <link href="~/TemplateManagement/vendors/dropify/dist/css/dropify.css" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="~/TemplateManagement/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" />

}


<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>@UsersManagementResources.Edite_FormTitle <small>@UsersManagementResources.Edite_FormDesc</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>

                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <div asp-validation-summary="All" class="text-danger"></div>
                <form id="demo-form2" method="post" enctype="multipart/form-data" data-parsley-validate class="form-horizontal form-label-left">
                    <input asp-for="Input.Id" type="hidden" />

                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="first-name">
                            @UsersManagementResources.FormImage
                        </label>
                        <div class="col-md-3 col-sm-6 ">
                            <input type="file" asp-for="Input.File" class="dropify" />
                        </div>
                        <div class="col-md-3 col-sm-6 ">
                            <img src="@Url.Page("/Index", "LoadUserImage", new { area = "",userName=Model.Input.UserName })" alt="..." class="img-circle profile_img">
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="first-name">
                            @UsersManagementResources.FormFirstName <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" asp-for="Input.FirstName" class="form-control  has-feedback-left">
                            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            <span asp-validation-for="Input.FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormMiddleName <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" asp-for="Input.MiddleName" class="form-control  has-feedback-left">
                            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            <span asp-validation-for="Input.MiddleName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormLastName <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" asp-for="Input.LastName" class="form-control  has-feedback-left">
                            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            <span asp-validation-for="Input.LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormBirthDate <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" class="form-control has-feedback-left" id="txt_birthDate" asp-for="Input.BirthDateString">
                            <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                            <span asp-validation-for="Input.BirthDateString" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormPhone <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" asp-for="Input.PhoneNumber" class="form-control  has-feedback-left">
                            <span class="fa fa-phone  form-control-feedback left" aria-hidden="true"></span>

                            <span asp-validation-for="Input.PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align"> @UsersManagementResources.FormGender</label>
                        <div class="col-md-6 col-sm-6 ">
                            <p>
                                @UsersManagementResources.FormMale :
                                @Html.RadioButtonFor(m => m.Input.GenderId, (int)Enumerations.GenderEnum.Male, new { @class = "flat" })
                                @UsersManagementResources.FormFemale :
                                @Html.RadioButtonFor(m => m.Input.GenderId, (int)Enumerations.GenderEnum.Female, new { @class = "flat" })
                            </p>
                            <span asp-validation-for="Input.GenderId" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormEmail <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <input type="text" asp-for="Input.Email" class="form-control  has-feedback-left">
                            <span class="fa fa-envelope form-control-feedback left" aria-hidden="true"></span>
                            <span asp-validation-for="Input.Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormUserName <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <span>@Model.Input.UserName</span>
                            <input type="hidden" asp-for="Input.UserName" />
                        </div>
                    </div>


                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @UsersManagementResources.FormAddress <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 ">
                            <textarea asp-for="Input.Address" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Input.Address" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-3 col-sm-3 label-align" for="last-name">
                            @SharedResources.Activate
                        </label>
                        <div class="col-md-9 col-sm-9 ">
                            <div class="">
                                <label>
                                    <input type="checkbox" asp-for="Input.Active" class="js-switch" />  @SharedResources.Activate /  @SharedResources.Deactivate
                                </label>

                            </div>

                        </div>
                    </div>
                    <div class="item form-group">
                        <label class="col-form-label col-md-3 col-sm-3 label-align"> @UsersManagementResources.FormRoles</label>

                        <div class="col-md-6 col-sm-6 ">
                            @foreach (var role in Model.RolesList)
                            {
                                <div class="checkbox">
                                    <label>
                                        <input type="checkbox" name="Input.Roles"
                                               value="@role.Name" class="flat" @(Model.Input.Roles.Contains(role.Name) ? "checked='checked'" : "")> @role.Name
                                        </label>
                                    </div>
                                }

                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 offset-md-3">
                            <button type="submit" asp-page-handler="Submit" class="btn btn-success">@SharedResources.Submit</button>
                            <button type="submit" asp-page-handler="Cancel" formnovalidate="formnovalidate" class="btn btn-primary">@SharedResources.BackToList</button>

                            &nbsp;
                            <button type="submit" asp-page-handler="Remove" asp-route-id="@Model.Input.Id" onclick="return confirm('@SharedResources.DeleteConfirm');" formnovalidate="formnovalidate" class="btn btn-danger">@SharedResources.Delete</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <!-- Switchery -->
    <script src="~/TemplateManagement/vendors/switchery/dist/switchery.min.js"></script>
    <!--dropify-->
    <script src="~/TemplateManagement/vendors/dropify/dist/js/dropify.min.js"></script>
    <!-- iCheck -->
    <script src="~/TemplateManagement/vendors/iCheck/icheck.min.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/TemplateManagement/vendors/moment/min/moment.min.js"></script>
    <script src="~/TemplateManagement/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <script src="~/ClientApp/UserManagementAdmin/Users/app.edite.js"></script>
    <script>
        $app.edite.Init();
    </script>
}